In [1]:
import pandas as pd
import os
import glob

# Define the folder where the CSV files were downloaded
folder_path = '../data/hourly_count/'

# Load all CSV files into a single DataFrame
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
df_list = [pd.read_csv(file) for file in csv_files]
df = pd.concat(df_list, ignore_index=True)

# Display the first few rows to verify
print(df.head())

   user_id  hour  hour_count  hour_ratio
0      396     0          82    0.067657
1      396     1          40    0.033003
2      396     2          75    0.061881
3      396     3          45    0.037129
4      396     4          49    0.040429

In [2]:
# Pivot the DataFrame to create hour_count_00~23 columns
hour_count_df = df.pivot(index='user_id', columns='hour', values='hour_count')
hour_count_df.columns = [f'hour_count_{str(col).zfill(2)}' for col in hour_count_df.columns]

# Pivot the DataFrame to create hour_ratio_00~23 columns
hour_ratio_df = df.pivot(index='user_id', columns='hour', values='hour_ratio')
hour_ratio_df.columns = [f'hour_ratio_{str(col).zfill(2)}' for col in hour_ratio_df.columns]

# Merge the two DataFrames
pivot_df = pd.merge(hour_count_df, hour_ratio_df, on='user_id', how='outer')

# Fill NaN values with 0 (if needed, depending on how you want to handle missing hours)
pivot_df.fillna(0, inplace=True)

# Reset index to make user_id a column
pivot_df.reset_index(inplace=True)

# Display the pivoted DataFrame
print(pivot_df.head())

   user_id  hour_count_00  hour_count_01  hour_count_02  hour_count_03  \
0      396           82.0           40.0           75.0           45.0
1     1096            0.0            0.0            0.0            0.0
2     1196            0.0            0.0            0.0            0.0
3     2996           64.0           78.0           38.0           29.0
4     3096           21.0            1.0            0.0            0.0

   hour_count_04  hour_count_05  hour_count_06  hour_count_07  hour_count_08  \
0           49.0           19.0           33.0           38.0           23.0
1            0.0            0.0            0.0            0.0            8.0
2            0.0            0.0            0.0            4.0            4.0
3            9.0            2.0            7.0           19.0           18.0
4            0.0            0.0            0.0            0.0           47.0

   ...  hour_ratio_14  hour_ratio_15  hour_ratio_16  hour_ratio_17  \
0  ...       0.004950       0.013201       0.049505       0.071782
1  ...       0.104651       0.186047       0.069767       0.000000
2  ...       0.032877       0.013699       0.063014       0.101370
3  ...       0.042872       0.030011       0.002144       0.028939
4  ...       0.005602       0.022409       0.000000       0.000000

   hour_ratio_18  hour_ratio_19  hour_ratio_20  hour_ratio_21  hour_ratio_22  \
0       0.089109       0.068482       0.037954       0.084983       0.051980
1       0.000000       0.000000       0.000000       0.000000       0.000000
2       0.224658       0.134247       0.120548       0.084932       0.010959
3       0.040729       0.073955       0.066452       0.095391       0.062165
4       0.000000       0.243697       0.061625       0.005602       0.030812

   hour_ratio_23
0       0.063531
1       0.000000
2       0.000000
3       0.035370
4       0.039216

[5 rows x 49 columns]

In [3]:
pivot_df

,user_id,hour_count_00,hour_count_01,hour_count_02,hour_count_03,hour_count_04,hour_count_05,hour_count_06,hour_count_07,hour_count_08,...,hour_ratio_14,hour_ratio_15,hour_ratio_16,hour_ratio_17,hour_ratio_18,hour_ratio_19,hour_ratio_20,hour_ratio_21,hour_ratio_22,hour_ratio_23
0,396,82.0,40.0,75.0,45.0,49.0,19.0,33.0,38.0,23.0,...,0.004950,0.013201,0.049505,0.071782,0.089109,0.068482,0.037954,0.084983,0.051980,0.063531
1,1096,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.104651,0.186047,0.069767,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,1196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,...,0.032877,0.013699,0.063014,0.101370,0.224658,0.134247,0.120548,0.084932,0.010959,0.000000
3,2996,64.0,78.0,38.0,29.0,9.0,2.0,7.0,19.0,18.0,...,0.042872,0.030011,0.002144,0.028939,0.040729,0.073955,0.066452,0.095391,0.062165,0.035370
4,3096,21.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,47.0,...,0.005602,0.022409,0.000000,0.000000,0.000000,0.243697,0.061625,0.005602,0.030812,0.039216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43202,60374096,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.010000,0.150000,0.060000,0.070000,0.100000,0.000000,0.000000,0.160000,0.040000,0.000000
43203,60374496,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.053191,0.106383,0.074468,0.085106,0.042553,0.085106,0.031915,0.127660,0.074468,0.106383
43204,60375796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.225352,0.000000,0.140845,0.154930,0.070423,0.154930,0.000000,0.000000,0.000000
43205,60375896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.116279,0.116279,0.124031,0.124031,0.085271,0.093023,0.031008,0.007752,0.069767,0.000000
43206,60376596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.050633,0.094937,0.107595,0.107595,0.107595,0.107595,0.107595,0.101266,0.107595,0.107595

In [4]:
pivot_df.to_csv("../data/hourly_count/processed/pivoted.csv")